# Generated by Django 3.2.16 on 2024-09-13 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CC_Extractor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='subtitle_file',
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_file', models.FileField(upload_to='subtitles/')),
                ('language', models.CharField(default='unknown', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='CC_Extractor.video')),
            ],
        ),
    ]
